import { axiosInstance } from '@/lib/api/axios';
import type { Difficulty, RubricCriterion, Style } from '@/lib/mockInterviews/constants';

/**
 * The admin mock-interview template surface.
 *
 * `scope` decides which of two questions the list answers: `mine` is
 * "templates I authored" (the admin list page) and `attachable` is "templates
 * I could attach to a course or path" (the pickers). The default is the
 * narrow one, so a caller that forgets shows an empty picker rather than a
 * wider list than intended.
 */

export type MockInterviewTemplate = {
  id: string;
  name: string;
  summary: string | null;
  description: string | null;
  company: string | null;
  position: string | null;
  seniority: string | null;
  style: Style | null;
  format: string | null;
  category: string | null;
  difficulty: Difficulty;
  duration: number;
  questions: number | null;
  topics: string[];
  evaluationRubric: RubricCriterion[];
  isPublic: boolean;
  /**
   * Overrides `isPublic` — the owner's visibility rule is
   * `public <=> isWaiting === false && isPublic === true`. A resubmitted
   * template can have `isPublic: true` and still not be public.
   */
  isWaiting: boolean;
  /** The instructor's submission note, or an admin's rejection feedback. */
  waitingLink: string | null;
  /** Server-owned: the template was generated by a learner from a job description. */
  isCustom: boolean;
  sourceJd: string | null;
  createdById: string | null;
  createdAt: string | null;
  attemptCount: number;
};

export type Attempt = {
  id: string;
  status: string;
  score: number | null;
  startedAt: string | null;
  completedAt: string | null;
  /**
   * Shaped by `personRow` (an allowlist, not a blocklist): every caller gets
   * the first five fields, and only platform staff also get the other five.
   * The staff-only keys are genuinely absent for an instructor — not
   * present-with-null — so they are optional here rather than nullable.
   */
  candidate: {
    name: string;
    avatar: string | null;
    progress: number | null;
    /** The learner's lifetime points total from `User`, not this attempt's score. */
    score: number | null;
    createdAt: string | null;
    id?: string | null;
    email?: string | null;
    username?: string | null;
    country?: string | null;
    isPremium?: boolean;
  };
};

export type TemplateDetail = MockInterviewTemplate & {
  attempts: {
    stats: {
      total: number;
      completed: number;
      completionRate: number | null;
      averageScore: number | null;
    };
    recent: Attempt[];
  };
};

/** Everything a client may write. Mirrors the API's Joi schema exactly. */
export type TemplateInput = Partial<
  Pick<
    MockInterviewTemplate,
    | 'name'
    | 'summary'
    | 'description'
    | 'company'
    | 'position'
    | 'seniority'
    | 'style'
    | 'format'
    | 'category'
    | 'difficulty'
    | 'duration'
    | 'questions'
    | 'topics'
    | 'evaluationRubric'
    | 'isPublic'
  >
>;

export type TemplateListParams = {
  page?: number;
  limit?: number;
  q?: string;
  scope?: 'mine' | 'attachable';
  style?: string;
  category?: string;
  difficulty?: string;
  status?: 'published' | 'draft';
};

export type PaginatedTemplates = {
  data: MockInterviewTemplate[];
  total: number;
  page: number;
  limit: number;
};

export async function fetchTemplates(params: TemplateListParams = {}): Promise<PaginatedTemplates> {
  const { data } = await axiosInstance.get('/admin/mock-interview-templates', { params });
  return data;
}

export async function fetchTemplate(id: string): Promise<TemplateDetail> {
  const { data } = await axiosInstance.get(`/admin/mock-interview-templates/${id}`);
  return data.data;
}

export async function createTemplate(payload: TemplateInput): Promise<MockInterviewTemplate> {
  const { data } = await axiosInstance.post('/admin/mock-interview-templates', payload);
  return data.data;
}

export async function updateTemplate(
  id: string,
  payload: TemplateInput,
): Promise<MockInterviewTemplate> {
  const { data } = await axiosInstance.put(`/admin/mock-interview-templates/${id}`, payload);
  return data.data;
}

export async function deleteTemplate(id: string): Promise<void> {
  await axiosInstance.delete(`/admin/mock-interview-templates/${id}`);
}
