/**
 * "Fill from JSON" is a shortcut for authors who already have the content —
 * typically generated by an assistant. It writes into the open form and
 * saves nothing: what reaches the API stays a decision the author makes by
 * pressing Save with the filled fields in front of them.
 *
 * The property that matters most here is the merge. `patch` writes only the
 * keys the JSON carried, so pasting a partial object can never wipe a field
 * the author already typed — these tests pin that end to end, through the
 * real form rather than against the parser alone.
 */
import React from 'react';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import { QueryClient, QueryClientProvider } from '@tanstack/react-query';

import ItemDrawer, { type DrawerTarget } from '../ItemDrawer';
import { itemSample } from '@/lib/courses/item-fill';

vi.mock('@/lib/api/axios', () => ({
  axiosInstance: { post: vi.fn(), get: vi.fn(), put: vi.fn(), delete: vi.fn() },
}));

function open(target: DrawerTarget) {
  // A NEW non-owned item opens on "Use existing", which renders LibraryPicker
  // and its react-query hook — hence the provider.
  const qc = new QueryClient({ defaultOptions: { queries: { retry: false } } });
  return render(
    <QueryClientProvider client={qc}>
      <ItemDrawer open target={target} courseId="course-1" onClose={() => {}} onSaved={() => {}} />
    </QueryClientProvider>,
  );
}

const videoTarget: DrawerTarget = { kind: 'video', chapterId: 'ch1' };

/**
 * A NEW item opens on the "Use existing" tab — reusing authored content is
 * usually the better move — so the create form, and the JSON panel with it,
 * lives behind "Create new".
 */
function openNew(target: DrawerTarget) {
  const result = open(target);
  const createNew = screen.queryByRole('button', { name: /create new/i });
  if (createNew) fireEvent.click(createNew);
  return result;
}

/** Opens the collapsed panel and returns its textarea. */
function openPanel() {
  fireEvent.click(screen.getByRole('button', { name: /fill from json/i }));
  return screen.getByLabelText(/json/i);
}

/**
 * Title is the first text box in the form, and `Field` does not associate its
 * label with the control, so there is no accessible name to query by. Read
 * with the JSON panel collapsed, or its CodeArea is first instead.
 */
function titleInput() {
  return screen.getAllByRole('textbox')[0] as HTMLInputElement;
}

function paste(json: string) {
  fireEvent.change(openPanel(), { target: { value: json } });
  fireEvent.click(screen.getByRole('button', { name: /^fill fields$/i }));
}

describe('ItemDrawer — fill from JSON', () => {
  it('stays out of the way until asked for', () => {
    openNew(videoTarget);
    // Collapsed: the code box must not push the real form below the fold for
    // the authors who are just typing.
    expect(screen.getByRole('button', { name: /fill from json/i })).toHaveAttribute(
      'aria-expanded',
      'false',
    );
    expect(screen.queryByLabelText(/json/i)).not.toBeInTheDocument();
  });

  it('fills the form fields from a pasted object', async () => {
    openNew(videoTarget);
    paste('{ "title": "Exactly-once is a lie", "video": "vimeo:912334477", "duration": 880 }');

    await waitFor(() =>
      expect(screen.getByDisplayValue('Exactly-once is a lie')).toBeInTheDocument(),
    );
    expect(screen.getByDisplayValue('vimeo:912334477')).toBeInTheDocument();
    expect(screen.getByDisplayValue('880')).toBeInTheDocument();
  });

  it('leaves a field the JSON never mentioned exactly as the author typed it', async () => {
    openNew(videoTarget);

    fireEvent.change(titleInput(), { target: { value: 'Typed by hand' } });

    paste('{ "video": "vimeo:1", "duration": 30 }');

    await waitFor(() => expect(screen.getByDisplayValue('vimeo:1')).toBeInTheDocument());
    // The paste carried no title, so the author's own title survives.
    expect(screen.getByDisplayValue('Typed by hand')).toBeInTheDocument();
  });

  it('closes itself after a successful fill, so the form is what you see next', async () => {
    openNew(videoTarget);
    paste('{ "title": "Filled" }');

    await waitFor(() => expect(screen.queryByLabelText(/json/i)).not.toBeInTheDocument());
  });

  it('changes nothing and stays open when the JSON is unusable', async () => {
    openNew(videoTarget);

    fireEvent.change(titleInput(), { target: { value: 'Still here' } });

    paste('{ not json ]');

    expect(screen.getByDisplayValue('Still here')).toBeInTheDocument();
    // Left open with the bad text still in it — there is something to fix.
    expect(screen.getByLabelText(/json/i)).toBeInTheDocument();
  });

  it('refuses a payload for a different kind rather than half-filling this one', async () => {
    openNew(videoTarget);
    paste('{ "kind": "quiz", "title": "A quiz, pasted into a video" }');

    expect(screen.queryByDisplayValue('A quiz, pasted into a video')).not.toBeInTheDocument();
    expect(screen.getByLabelText(/json/i)).toBeInTheDocument();
  });

  it('inserts a sample that fills its own form', async () => {
    openNew(videoTarget);
    openPanel();
    fireEvent.click(screen.getByRole('button', { name: /insert sample/i }));

    expect(screen.getByLabelText(/json/i)).toHaveValue(itemSample('video'));

    fireEvent.click(screen.getByRole('button', { name: /^fill fields$/i }));
    await waitFor(() =>
      expect(screen.getByDisplayValue('Exactly-once is a lie')).toBeInTheDocument(),
    );
  });

  it('fills an exercise, including its nested test cases', async () => {
    openNew({ kind: 'exercise', chapterId: 'ch1' });
    paste(
      JSON.stringify({
        title: 'Deduplicate a stream',
        points: 20,
        testCases: [{ input: '1 1 2', expectedOutput: '1 2' }],
      }),
    );

    await waitFor(() =>
      expect(screen.getByDisplayValue('Deduplicate a stream')).toBeInTheDocument(),
    );
    expect(screen.getByDisplayValue('1 1 2')).toBeInTheDocument();
    expect(screen.getByDisplayValue('1 2')).toBeInTheDocument();
  });

  it('is not offered for a chapter — four short fields need no JSON box', () => {
    openNew({ kind: 'chapter' });
    expect(screen.queryByRole('button', { name: /fill from json/i })).not.toBeInTheDocument();
  });
});
